base_url = "https://www.lexyart.com"
title = "Lexy Eclipse"
description = "Tatuagem, Body Piercing, e Tarot"
default_language = "pt"

[extra]
autor = "Lexy Eclipse"
social = [
  { name = "Instagram", url = "https://instagram.com/lexyeclipse", icon = "instagram" },
  { name = "WhatsApp", url = "https://wa.me/5538997408087", icon = "whatsapp" }
]
navbar = [
    { path = "/galeria/" },
    { path = "/sobre/" },
]
