base_url = "https://exemplo.com"
title = "Lexy Eclipse"
description = "Presente de aniversário em forma de site :)"
default_language = "pt"

[extra]
autor = "Lexy Eclipse"
social = [
  { name = "Instagram", url = "https://instagram.com/lexyeclipse", icon = "instagram" },
  { name = "WhatsApp", url = "https://wa.me/5538997408087", icon = "whatsapp" }
]

