services:
  zola:
    image: ghcr.io/getzola/zola:v0.19.1
    user: "1000:1000"
    volumes:
      - .:/site
    working_dir: /site
    command: ["build", "--output-dir", "public", "--force"]

  zola-serve:
    image: ghcr.io/getzola/zola:v0.19.1
    user: "1000:1000"
    volumes:
      - .:/site
    working_dir: /site
    command: ["serve", "--interface", "0.0.0.0", "--port", "1111"]
    ports:
      - "1111:1111"

