services:
  zola:
    image: ghcr.io/getzola/zola:v0.19.1
    user: "1000:1000"
    volumes:
      - .:/site
    working_dir: /site
    command: ["build", "--output-dir", "public", "--force"]

  zola-serve:
    image: ghcr.io/getzola/zola:v0.19.1
    user: "1000:1000"
    volumes:
      - .:/site
    working_dir: /site
    command: ["serve", "--interface", "0.0.0.0", "--port", "1111"]
    ports:
      - "1111:1111"
      - "1024:1024"

  yamllint:
    image: cytopia/yamllint
    volumes:
      - .:/data
    working_dir: /data
    entrypoint: yamllint

  markdownlint:
    image: node:18-alpine
    volumes:
      - .:/site
    working_dir: /site
    entrypoint: sh
    command: ["-c", "npm install -g markdown-link-check && markdown-link-check -q -c .mlc_config.json ."]
